// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('AssessmentController', function($scope, $http) {
    $scope.assessmentRequest = '{"id": "' + $scope.form.id + '"}';
    $scope.assessmentResult = {};
    return $scope.close = function() {
      return $http.put('../api/publishing/opendata/assess', $scope.assessmentRequest).success(function(result) {
        return $scope.$close(result.record);
      })["catch"](function(error) {
        $scope.notifications.add(error.data.exceptionMessage);
        return $scope.$dismiss();
      });
    };
  });

}).call(this);

//# sourceMappingURL=AssessmentController.js.map
