// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('AssessmentController', function($scope, $http) {
    var formatDate, refreshAssessmentButton, useTwoDigits;
    formatDate = function(date) {
      var day, month, year;
      year = date.getFullYear();
      month = useTwoDigits(date.getMonth() + 1);
      day = useTwoDigits(date.getDate());
      return "" + day + "/" + month + "/" + year;
    };
    useTwoDigits = function(val) {
      if (val < 10) {
        return "0" + val;
      }
      return val;
    };
    $scope.assessmentRequest = {};
    $scope.assessmentRequest.id = $scope.form.id;
    $scope.assessmentWidth = "85%";
    $scope.signOffWidth = "15%";
    $scope.showSignOffInfo = $scope.form.publication !== null && $scope.form.publication.openData.completed;
    $scope.signOffButtonDisabled = !$scope.user.isIaoUser || ($scope.form.publication !== null && $scope.form.publication.openData.signOff !== null);
    refreshAssessmentButton = function() {
      if ($scope.form.publication !== null && $scope.form.publication.openData.assessment.completed) {
        if ($scope.form.publication.openData.assessment.initialAssessmentWasDoneOnSpreadsheet) {
          return $scope.assessmentButtonText = "Initial assessment completed on spreadsheet";
        } else {
          return $scope.assessmentButtonText = "Completed by " + $scope.form.publication.openData.assessment.completedByUser.displayName + " on " + formatDate(new Date($scope.form.publication.openData.assessment.completedOnUtc));
        }
      } else {
        return $scope.assessmentButtonText = "I AGREE";
      }
    };
    refreshAssessmentButton();
    if ($scope.form.publication !== null && $scope.form.publication.openData.signOff !== null) {
      $scope.signOffButtonText = "Signed off by " + $scope.form.publication.openData.signOff.user.displayName + " on " + formatDate(new Date($scope.form.publication.openData.signOff.dateUtc));
    } else if ($scope.user.isIaoUser) {
      $scope.signOffButtonText = "SIGN OFF";
    } else {
      $scope.signOffButtonText = "Pending sign off";
    }
    $scope.assessClick = function() {
      return $http.put('../api/publishing/opendata/assess', $scope.assessmentRequest).success(function(result) {
        $scope.status.refresh();
        $scope.expandSignOff();
        $scope.form = result.record;
        return refreshAssessmentButton();
      })["catch"](function(error) {
        $scope.notifications.add(error.data.exceptionMessage);
        return $scope.$dismiss();
      });
    };
    $scope.expandSignOff = function() {
      $scope.assessmentWidth = "50%";
      return $scope.signOffWidth = "50%";
    };
    return $scope.close = function() {
      return $scope.$close($scope.form);
    };
  });

}).call(this);

//# sourceMappingURL=AssessmentController.js.map
