// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('ContentController', function($scope) {
    return $scope.slide = 0;
  });

}).call(this);

//# sourceMappingURL=ContentController.js.map
