// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('ImagePickerController', function($scope, $http, recordOutput) {
    $scope.test = "hello";
    return $scope.close = function() {
      return $scope.$close($scope.recordOutput);
    };
  });

}).call(this);

//# sourceMappingURL=ImagePickerController.js.map
