// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers', ['ui.bootstrap']).controller('MainController', function($scope, $rootScope, $timeout, $cookies, $http, Account) {
    var busyCount, notifications;
    $scope.page = {
      title: 'Topcat'
    };
    busyCount = 0;
    $scope.busy = {
      start: function() {
        return busyCount = busyCount + 1;
      },
      stop: function() {
        return busyCount = busyCount - 1;
      },
      value: function() {
        return busyCount > 0;
      }
    };
    notifications = [];
    $scope.notifications = {
      current: notifications,
      add: function(message) {
        var n, remove;
        n = {
          message: message
        };
        notifications.push(n);
        remove = function() {
          return notifications.pop();
        };
        return $timeout(remove, 4000);
      }
    };
    Account.then(function(user) {
      return $scope.user = user;
    });
    $scope.status = {
      pendingSignOffCount: 0,
      refresh: function() {
        return $http.get('../api/publishing/pendingsignoffcountforcurrentuser').success(function(result) {
          return $scope.status.pendingSignOffCount = result;
        });
      }
    };
    $scope.status.refresh();
    return $rootScope.$on('$locationChangeStart', function() {
      return $('.qtip').qtip('hide');
    });
  });

}).call(this);

//# sourceMappingURL=MainController.js.map
