// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('OpenDataModalController', function($scope, $http, $timeout) {
    var formatDate, publishingStatus, refreshAssessmentButton, refreshSignOffButton, useTwoDigits;
    formatDate = function(date) {
      var day, month, year;
      year = date.getFullYear();
      month = useTwoDigits(date.getMonth() + 1);
      day = useTwoDigits(date.getDate());
      return "" + day + "/" + month + "/" + year;
    };
    useTwoDigits = function(val) {
      if (val < 10) {
        return "0" + val;
      }
      return val;
    };
    $scope.assessmentRequest = {};
    $scope.assessmentRequest.id = $scope.form.id;
    publishingStatus = {
      riskAssessment: {
        currentClass: {},
        completed: {}
      },
      signOff: {
        currentClass: {},
        completed: {},
        timeout: {},
        signOffButtonDisabled: {},
        signOffButtonClass: {}
      },
      upload: {
        currentClass: {},
        completed: {}
      },
      currentActiveView: {}
    };
    $scope.publishingStatus = publishingStatus;
    publishingStatus.signOff.timeout = 0;
    $scope.refreshPublishingStatus = function() {
      publishingStatus.riskAssessment.completed = $scope.form.publication !== null && $scope.form.publication.openData.assessment.completed;
      publishingStatus.signOff.completed = $scope.form.publication !== null && $scope.form.publication.openData.signOff !== null;
      publishingStatus.upload.completed = $scope.form.publication !== null && $scope.form.publication.openData.lastSuccess !== null;
      if (publishingStatus.upload.completed) {
        publishingStatus.riskAssessment.currentClass = "visited";
        publishingStatus.signOff.currentClass = "visited";
        return publishingStatus.upload.currentClass = "visited";
      } else if (publishingStatus.signOff.completed) {
        publishingStatus.riskAssessment.currentClass = "visited";
        publishingStatus.signOff.currentClass = "visited";
        return publishingStatus.upload.currentClass = "current";
      } else if (publishingStatus.riskAssessment.completed) {
        publishingStatus.riskAssessment.currentClass = "visited";
        publishingStatus.signOff.currentClass = "current";
        return publishingStatus.upload.currentClass = "disabled";
      } else {
        publishingStatus.riskAssessment.currentClass = "current";
        publishingStatus.signOff.currentClass = "disabled";
        return publishingStatus.upload.currentClass = "disabled";
      }
    };
    $scope.refreshPublishingStatus();
    if (publishingStatus.upload.completed || publishingStatus.signOff.completed) {
      publishingStatus.currentActiveView = "upload";
    } else if (publishingStatus.riskAssessment.completed) {
      publishingStatus.currentActiveView = "sign off";
    } else {
      publishingStatus.currentActiveView = "risk assessment";
    }
    refreshAssessmentButton = function() {
      if ($scope.form.publication !== null && $scope.form.publication.openData.assessment.completed) {
        if ($scope.form.publication.openData.assessment.initialAssessmentWasDoneOnSpreadsheet) {
          return $scope.assessmentButtonText = "Initial assessment completed on spreadsheet";
        } else {
          return $scope.assessmentButtonText = "Completed by " + $scope.form.publication.openData.assessment.completedByUser.displayName + " on " + formatDate(new Date($scope.form.publication.openData.assessment.completedOnUtc));
        }
      } else {
        return $scope.assessmentButtonText = "I AGREE";
      }
    };
    refreshSignOffButton = function() {
      publishingStatus.signOff.signOffButtonDisabled = !$scope.user.isIaoUser || ($scope.form.publication !== null && $scope.form.publication.openData.signOff !== null);
      if ($scope.form.publication !== null && $scope.form.publication.openData.signOff !== null) {
        publishingStatus.signOff.signOffButtonClass = "btn btn-primary";
        return publishingStatus.signOff.signOffButtonText = "Signed off by " + $scope.form.publication.openData.signOff.user.displayName + " on " + formatDate(new Date($scope.form.publication.openData.signOff.dateUtc));
      } else if ($scope.user.isIaoUser) {
        publishingStatus.signOff.signOffButtonClass = "btn btn-danger sign-off";
        return publishingStatus.signOff.signOffButtonText = "SIGN OFF";
      } else {
        publishingStatus.signOff.signOffButtonClass = "btn btn-primary";
        return publishingStatus.signOff.signOffButtonText = "Pending sign off";
      }
    };
    refreshAssessmentButton();
    refreshSignOffButton();
    $scope.assessButtonClick = function() {
      return $http.put('../api/publishing/opendata/assess', $scope.assessmentRequest).success(function(result) {
        $scope.status.refresh();
        $scope.form = result.record;
        refreshAssessmentButton();
        $scope.refreshPublishingStatus();
        return publishingStatus.currentActiveView = "sign off";
      })["catch"](function(error) {
        $scope.notifications.add(error.data.exceptionMessage);
        return $scope.$dismiss();
      });
    };
    $scope.signOffButtonClick = function() {
      if (publishingStatus.signOff.timeout === 0) {
        publishingStatus.signOff.timeout = 10;
        return $scope.allowGraceTime();
      } else {
        return $scope.cancelSignOff();
      }
    };
    $scope.submitSignOff = function() {
      $scope.signOffRequest = {
        id: $scope.form.id,
        comment: ""
      };
      return $http.put('../api/publishing/opendata/signoff', $scope.signOffRequest).success(function(result) {
        $scope.status.refresh();
        $scope.form = result.record;
        refreshSignOffButton();
        $scope.refreshPublishingStatus();
        return publishingStatus.currentActiveView = "upload";
      })["catch"](function(error) {
        if (error.status === 401) {
          $scope.notifications.add("Unauthorised - not in valid sign off group");
        } else {
          $scope.notifications.add(error.data.exceptionMessage);
        }
        publishingStatus.signOff.timeout = 0;
        return $scope.$dismiss();
      });
    };
    $scope.allowGraceTime = function() {
      if (publishingStatus.signOff.timeout > 0) {
        publishingStatus.signOff.signOffButtonText = "Cancel " + ("0" + publishingStatus.signOff.timeout--).slice(-2);
        return $timeout($scope.allowGraceTime, 1000);
      } else {
        return $scope.submitSignOff();
      }
    };
    $scope.cancelSignOff = function() {
      publishingStatus.signOff.timeout = 0;
      return refreshSignOffButton();
    };
    return $scope.close = function() {
      return $scope.$close($scope.form);
    };
  });

}).call(this);

//# sourceMappingURL=OpenDataModalController.js.map
