// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('OpenDataPublishingController', function($scope, $http) {
    var load1, load2, load3, load4, loadList, m;
    m = {
      tab: 2,
      openData: {
        summary: {},
        list: []
      }
    };
    $scope.m = m;
    $http.get('../api/publishing/opendata/summary').success(function(result) {
      return m.openData.summary = result;
    });
    load1 = function() {
      return $http.get('../api/publishing/opendata/publishedsincelastupdated').success(function(result) {
        return m.openData.list = result;
      });
    };
    load2 = function() {
      return $http.get('../api/publishing/opendata/notpublishedsincelastupdated').success(function(result) {
        return m.openData.list = result;
      });
    };
    load3 = function() {
      return $http.get('../api/publishing/opendata/publicationneverattempted').success(function(result) {
        return m.openData.list = result;
      });
    };
    load4 = function() {
      return $http.get('../api/publishing/opendata/lastpublicationattemptwasunsuccessful').success(function(result) {
        return m.openData.list = result;
      });
    };
    loadList = function() {
      switch (m.tab) {
        case 1:
          return load1();
        case 2:
          return load2();
        case 3:
          return load3();
        case 4:
          return load4();
      }
    };
    $scope.$watch('m.tab', loadList);
    return load2();
  });

}).call(this);

//# sourceMappingURL=OpenDataPublishingController.js.map
