// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('PublishingController', function($scope, $http) {
    $scope.opendata = {};
    $http.get('../api/publishing/opendata/summary').success(function(result) {
      return $scope.opendata.summary = result;
    });
    return $http.get('../api/publishing/opendata/pending').success(function(result) {
      return $scope.opendata.pending = result;
    });
  });

}).call(this);

//# sourceMappingURL=PublishingController.js.map
