// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('PublishingController', function($scope, $http) {
    var m;
    m = {
      openData: {},
      tab: 2
    };
    $scope.m = m;
    $http.get('../api/publishing/opendata/summary').success(function(result) {
      return m.openData.summary = result;
    });
    return $http.get('../api/publishing/opendata/pending').success(function(result) {
      return m.openData.pending = result;
    });
  });

}).call(this);

//# sourceMappingURL=PublishingController.js.map
