// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('app.controllers').controller('SandboxController', function($scope) {
    return $scope.x = 3;
  });

}).call(this);

//# sourceMappingURL=SandboxController.map
