// Generated by IcedCoffeeScript 108.0.11
(function() {
  var module;

  module = angular.module('app.config');

  module.constant('imagePickerUrl', 'http://217.168.21.93/umbraco/api/imagepickerapi/get?id=1064');

}).call(this);

//# sourceMappingURL=config.js.map
