// Generated by IcedCoffeeScript 108.0.11
(function() {
  var module;

  module = angular.module('app.config');

  module.constant('signOffGroup', 'OpenDataIAO');

}).call(this);

//# sourceMappingURL=config.js.map
